### ISSUE TITLE
Compilation error with ozzo validator.

### ISSUE THREAD

**Issue by hsblhsn** [mikekonan/go-types#8]
cannot use`r.Country` (variable of type `country.Alpha2Code`) as validation.Rule value in argument to validation.Field: wrong type for method Validate (have `func() (err error)`, want `func(value interface{}) error)`

### My Code

```go
package foo

import (
    validation "github.com/go-ozzo/ozzo-validation"
    "github.com/mikekonan/go-types/country"
)

type Foo struct {
    CountryCode country.Alpha2Code
}
func (r *Foo) Validate() error {
    return validation.ValidateStruct(r,
        validation.Field(r.Country, validation.Required, r.Country),
    ),
}
```

**Comment by hsblhsn** [comment]
Currently using this as hotfix.

```go
validation.By(func(value interface{}) error {
    v, _ := value.(country.Alpha2Code)
    return v.Validate()
}),
```

**Comment by hsblhsn** [comment]
Currently using this as hotfix.

```go
validation.By(func(value interface{}) error {
    v, _ := value.(country.Alpha2Code)
    return v.Validate()
}),
```

**Comment by mikekonan** [comment]
You don't need to use validation.Required in validation.Field, this type acts like enum, so the empty value is not a valid enum option.

**Comment by mikekonan** [comment]
I've corrected the README
